branch-defaults:
  main:
    environment: inat-cards-env
environment-defaults:
  inat-cards-env: 
    branch: master
    repository: https://github.com/bruceMacLeod/inat-cards-backend.git
global:
  application_name: inat-cards-backend
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: us-east-2
  sc: git


